name: Build and Push to Docker Hub

on:
  workflow_dispatch:  # Permet executar manualment

jobs:
  build:
    runs-on: ubuntu-latest  # Linux, no Windows!
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      
      - name: Build and Push Backend
        run: |
          cd backend
          docker build -t urkovitx/mobil-scan-backend:latest .
          docker push urkovitx/mobil-scan-backend:latest
      
      - name: Build and Push Frontend
        run: |
          cd frontend
          docker build -t urkovitx/mobil-scan-frontend:latest .
          docker push urkovitx/mobil-scan-frontend:latest
      
      - name: Success
        run: echo "âœ… Imatges pujades a Docker Hub!"
